; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Optimizer
AppVersion=1.5
WizardStyle=modern
DefaultDirName={autopf}\Optimizer
DefaultGroupName=Optimizer
UninstallDisplayIcon={app}\Optimizer.exe
Compression=lzma2
SolidCompression=yes
; OutputDir=userdocs:Inno Setup Examples Output


[Files]
;Source: "Optimizer.exe"; DestDir: "{app}"
Source: "ExternalData\Powerplan\Power scheme.pow"; DestDir: "{app}\ExternalData\Powerplan"
Source: "ExternalData\Batchs\deltemp.bat"; DestDir: "{app}\ExternalData\Batchs"
Source: "ExternalData\Reg Files\Windows Privacy script.reg"; DestDir: "{app}\ExternalData\Reg Files"